### ISSUE TITLE
Альт-клик по надетому предмету или контейнеру в инвентаре открывает окно тайла

### ISSUE THREAD

**Issue by pro100Player** [ChaoticOnyx/BeeStation#16]
### Описание бага
При попытке открыть коробку в инвентаре или извлечь из сапога медручку альт-кликом открывается окно тайла, что вызывает лаг.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Убираем в сапог медручку;
2. Пытаемся извлечь её альткликом;
3. Открываются окно тайла (что и вызывает лаг) и инвентарь сапога, ручка не извлекается;
4. (Вероятное) Из-за лага заходим в лаву и вас гибает дрейк.

### Ожидаемое поведение
При клике по сапогу с медручкой оная оказывается в руке.
При клике по контейнеру надетому или находящемся в инвентаре открывается инвентарь.

**Comment by Doster-d** [comment]
Вот бы нам такого бота.
