### ISSUE TITLE
БАГ: фразы на русском в памяти генокрада ломаются, если отображаются в отдельно notes-окне. 

### ISSUE THREAD

**Issue by wadangel** [ChaoticOnyx/BeeStation#8]
При отображении в чате всё норм. 
(алсо сделайте шаблондля репорта на русском) 
![unknown-257](https://user-images.githubusercontent.com/29904082/93711296-3604c000-fb5e-11ea-8c71-b061779dda49.png)

**Comment by kcalbCube** [comment]
Оно мертво. Ажал.
